#!/usr/bin/env bash
# Generate a tmux-powerline theme from tubular's RESOLVED palette (the
# @_tubular_* options — the applier runs tubular before the layout sources,
# so these always hold the live theme's colors). tmux-powerline re-sources
# its config + theme on every status render, so a regenerated file takes
# effect on the next refresh with no plugin reload.
#
# Follows tmux-powerline's README recipe ("copy themes/default.sh and edit"):
# the generated theme sets ONLY colors and segment lists, then sources the
# plugin's stock default.sh for everything else — separators, patched-font
# glyph selection, window-status formats. The powerline arrow glyphs live in
# the plugin's own file and never pass through this generator (hand-writing
# them is exactly how they got lost once).
#
# Writes (marker-guarded — refuses to clobber files it didn't generate):
#   ~/.config/tmux-powerline/config.sh          theme selection + patched font
#   ~/.config/tmux-powerline/themes/tubular-live.sh
#
# Run by layouts/03-tmux-powerline.tmux BEFORE powerline's main.tmux, and
# re-run automatically whenever the theme or layout cycles.

MARK="# GENERATED by the tubular demo (tubular-powerline-theme-gen.sh)"
CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline"
CFG="$CFG_DIR/config.sh"
THEME_DIR="$CFG_DIR/themes"
THEME_FILE="$THEME_DIR/tubular-live.sh"

get() { tmux show-option -gqv "@_tubular_$1"; }
bg=$(get bg); bg_min=$(get bg_min); bg_max=$(get bg_max)
fg=$(get fg); nv=$(get neutral_visible); nh=$(get neutral_hidden)
active=$(get active_color)
[ -n "$bg" ] || { echo "tubular palette not resolved (run tubular.tmux first)" >&2; exit 1; }

for f in "$CFG" "$THEME_FILE"; do
  if [ -f "$f" ] && ! grep -qF "$MARK" "$f"; then
    echo "refusing to overwrite non-generated $f" >&2; exit 1
  fi
done
mkdir -p "$THEME_DIR"

cat > "$CFG" <<EOF
# shellcheck shell=bash
$MARK
export TMUX_POWERLINE_THEME="tubular-live"
export TMUX_POWERLINE_DIR_USER_THEMES="$THEME_DIR"
# Nerd Font present (tubular itself renders PUA glyphs), so use the real
# powerline arrows rather than the ▶ fallbacks.
export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"
EOF

cat > "$THEME_FILE" <<EOF
# shellcheck shell=bash
$MARK
# Regenerated on every tubular theme/layout switch — do not edit.
#
# Per the tmux-powerline README, this is a copy-and-edit of themes/default.sh
# — expressed as override-then-source: default.sh keeps any of these values
# that are already set (\${VAR:-...} / [ -z ... ] guards), and everything not
# set here (separator glyphs, window-status formats) stays stock.

TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR='$bg_max'
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR='$nv'

TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
	"tmux_session_info $active $bg"
	"hostname $bg_min $fg"
	"pwd $nh $fg"
)

TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
	"date_day $nh $fg"
	"date $bg_min $fg"
	"time $active $bg"
)

# shellcheck disable=SC1091
source "\$TMUX_POWERLINE_DIR_HOME/themes/default.sh"
EOF
